Repository entrymaster/cpograms, pull requests merged in 2020-10, with the labels that each got.

#2 Quick Sort Code
  Bubble Sort
Labels: hactoberfest

#3 Insertion Sort
  Insertion sort
Labels: hacktoberfest-accepted

#4 Create Binary search
  Binary search
Labels: hacktoberfest-accepted

#5 Linear Search
  Linear Search
Labels: hacktoberfest-accepted

#6 matrix multiplying
  matrix multiplying
Labels: hacktoberfest-accepted

#8 Create linked_list.c
  linked_list.c
Labels: hactoberfest

#9 Create most_freq_digit.c
  most_freq_digit.c
Labels: good first issue, hacktoberfest-accepted

#10 Create word_reverse.cpp
  word_reverse.cpp
Labels: hacktoberfest-accepted

#11 Create split_logic.cpp
  split_logic.cpp
Labels: hacktoberfest-accepted

#12 Create stact_ds_implem.c
  stact_ds_implem.c
Labels: hacktoberfest-accepted
